---
- name: ensure directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
    recurse: true
  loop:
    - /data/containers/certbot/bin
    - /data/containers/certbot/post
    - /data/containers/certbot/etc/letsencrypt/ca

- name: ensure secrets directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: root
    group: root
    recurse: true
  loop:
    - /data/containers/certbot/secrets

- name: deploy secrets
  include_role:
    name: novicecpp.homeserver.pass_deploy_secrets
  vars:
    pass_deploy_secrets_pass_path: "{{ certbot_secret_pass_path }}"
    pass_deploy_secrets_secret_path: /data/containers/certbot/secrets/digitalocean.ini
    pass_deploy_secrets_pass_template: |
      dns_digitalocean_token = ###pass_deploy_secrets_value###

- name: copy systemd unit
  ansible.builtin.copy:
    src: etc/systemd/system/
    dest: /etc/systemd/system/
    mode: '0644'
    owner: root
    group: root


- name: copy certbot scripts
  ansible.builtin.copy:
    src: certbot/bin/certbot.sh
    dest: /data/containers/certbot/bin/certbot.sh
    mode: '0755'
    owner: root
    group: root

- name: copy certbot post scripts
  ansible.builtin.copy:
    src: certbot/post/
    dest: /data/containers/certbot/post/
    mode: '0755'
    owner: root
    group: root

- name: get letsencrypt staging root ca
  block:
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: directory
        suffix: temp
      register: tempdir
    - name: get root cert (staging) x1
      ansible.builtin.get_url:
        url: https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem
        dest: /tmp/letsencrypt-stg-root-x1.pem
        checksum: sha256:3a5e1171e5f5c2d41522d438f225602e4236a68fb29c32399a95921a4ae80e73

    - name: get root cert (staging) x2
      ansible.builtin.get_url:
        url: https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x2.pem
        dest: /tmp/letsencrypt-stg-root-x2.pem
        checksum: sha256:497c36c1b50c0daff30870d5908c9b97af29223d5510c5e6c24957d0cc502fb8
    - name: cat
      ansible.builtin.shell: cat /tmp/letsencrypt-stg-root-x1.pem /tmp/letsencrypt-stg-root-x2.pem
      register: staging_root_cert_content
      changed_when: false
  always:
    - name: remove tempdir
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
      when: tempdir.path is defined

- name: copy root cert staging
  ansible.builtin.copy:
    content: "{{ staging_root_cert_content.stdout }}"
    dest: /data/containers/certbot/etc/letsencrypt/ca/letsencrypt-stg-root.pem
    mode: '0644'
    owner: root
    group: root

- name: start systemd timer
  ansible.builtin.systemd:
    state: started
    name: certbot.timer
    daemon_reload: true
    enabled: true
