---
- name: enable iptables unit
  ansible.builtin.systemd_service:
    name: iptables
    state: started
    enabled: true

- name: copy iptables rules
  ansible.builtin.copy:
    src: etc/iptables/iptables.rules
    dest: /etc/iptables/iptables.rules
    mode: '0644'
    owner: root
    group: root
  notify: restart iptables
