---
- name: copy systemd-resolved config
  ansible.builtin.copy:
    src: etc/systemd/resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart systemd-resovled
  become: true

- name: enable systemd-resolve now
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: started
    enabled: true
  become: true
